services:
  huh.member.entity.address:
    class: HeimrichHannot\MemberBundle\Entity\MemberAddress
    public: true
    arguments:
      - "@contao.framework"
  huh.member.entity.member:
    class: HeimrichHannot\MemberBundle\Entity\Member
    public: true
    arguments:
      - "@contao.framework"
  huh.member.choice.city:
    class: HeimrichHannot\MemberBundle\Choice\CityChoice
    public: true
    arguments:
      - "@contao.framework"
  huh.member.hooks:
    class: HeimrichHannot\MemberBundle\Backend\Hooks
    public: true
  huh.member.manager.registration:
    class: HeimrichHannot\MemberBundle\Manager\RegistrationManager
    public: true
    arguments:
      - "@contao.framework"
  huh.member.manager.message:
    class: HeimrichHannot\MemberBundle\Manager\MemberMessageManager
    public: true
    arguments:
      - "@contao.framework"